// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Connect.proto

package org.remoteandroid.ui.connect;

public final class ConnectMessages {
  private ConnectMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface CandidatesOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // repeated fixed32 internetIpv4 = 10;
    java.util.List<java.lang.Integer> getInternetIpv4List();
    int getInternetIpv4Count();
    int getInternetIpv4(int index);
    
    // repeated bytes internetIpv6 = 11;
    java.util.List<com.google.protobuf.ByteString> getInternetIpv6List();
    int getInternetIpv6Count();
    com.google.protobuf.ByteString getInternetIpv6(int index);
    
    // repeated fixed32 intranetIpv4 = 21;
    java.util.List<java.lang.Integer> getIntranetIpv4List();
    int getIntranetIpv4Count();
    int getIntranetIpv4(int index);
    
    // repeated bytes intranetIpv6 = 22;
    java.util.List<com.google.protobuf.ByteString> getIntranetIpv6List();
    int getIntranetIpv6Count();
    com.google.protobuf.ByteString getIntranetIpv6(int index);
    
    // optional bytes bssid = 20;
    boolean hasBssid();
    com.google.protobuf.ByteString getBssid();
    
    // optional fixed32 bluetoothMac = 30;
    boolean hasBluetoothMac();
    int getBluetoothMac();
    
    // optional bool bluetoothAnonmymous = 31;
    boolean hasBluetoothAnonmymous();
    boolean getBluetoothAnonmymous();
  }
  public static final class Candidates extends
      com.google.protobuf.GeneratedMessageLite
      implements CandidatesOrBuilder {
    // Use Candidates.newBuilder() to construct.
    private Candidates(Builder builder) {
      super(builder);
    }
    private Candidates(boolean noInit) {}
    
    private static final Candidates defaultInstance;
    public static Candidates getDefaultInstance() {
      return defaultInstance;
    }
    
    public Candidates getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // repeated fixed32 internetIpv4 = 10;
    public static final int INTERNETIPV4_FIELD_NUMBER = 10;
    private java.util.List<java.lang.Integer> internetIpv4_;
    public java.util.List<java.lang.Integer>
        getInternetIpv4List() {
      return internetIpv4_;
    }
    public int getInternetIpv4Count() {
      return internetIpv4_.size();
    }
    public int getInternetIpv4(int index) {
      return internetIpv4_.get(index);
    }
    
    // repeated bytes internetIpv6 = 11;
    public static final int INTERNETIPV6_FIELD_NUMBER = 11;
    private java.util.List<com.google.protobuf.ByteString> internetIpv6_;
    public java.util.List<com.google.protobuf.ByteString>
        getInternetIpv6List() {
      return internetIpv6_;
    }
    public int getInternetIpv6Count() {
      return internetIpv6_.size();
    }
    public com.google.protobuf.ByteString getInternetIpv6(int index) {
      return internetIpv6_.get(index);
    }
    
    // repeated fixed32 intranetIpv4 = 21;
    public static final int INTRANETIPV4_FIELD_NUMBER = 21;
    private java.util.List<java.lang.Integer> intranetIpv4_;
    public java.util.List<java.lang.Integer>
        getIntranetIpv4List() {
      return intranetIpv4_;
    }
    public int getIntranetIpv4Count() {
      return intranetIpv4_.size();
    }
    public int getIntranetIpv4(int index) {
      return intranetIpv4_.get(index);
    }
    
    // repeated bytes intranetIpv6 = 22;
    public static final int INTRANETIPV6_FIELD_NUMBER = 22;
    private java.util.List<com.google.protobuf.ByteString> intranetIpv6_;
    public java.util.List<com.google.protobuf.ByteString>
        getIntranetIpv6List() {
      return intranetIpv6_;
    }
    public int getIntranetIpv6Count() {
      return intranetIpv6_.size();
    }
    public com.google.protobuf.ByteString getIntranetIpv6(int index) {
      return intranetIpv6_.get(index);
    }
    
    // optional bytes bssid = 20;
    public static final int BSSID_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString bssid_;
    public boolean hasBssid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getBssid() {
      return bssid_;
    }
    
    // optional fixed32 bluetoothMac = 30;
    public static final int BLUETOOTHMAC_FIELD_NUMBER = 30;
    private int bluetoothMac_;
    public boolean hasBluetoothMac() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getBluetoothMac() {
      return bluetoothMac_;
    }
    
    // optional bool bluetoothAnonmymous = 31;
    public static final int BLUETOOTHANONMYMOUS_FIELD_NUMBER = 31;
    private boolean bluetoothAnonmymous_;
    public boolean hasBluetoothAnonmymous() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getBluetoothAnonmymous() {
      return bluetoothAnonmymous_;
    }
    
    private void initFields() {
      internetIpv4_ = java.util.Collections.emptyList();;
      internetIpv6_ = java.util.Collections.emptyList();;
      intranetIpv4_ = java.util.Collections.emptyList();;
      intranetIpv6_ = java.util.Collections.emptyList();;
      bssid_ = com.google.protobuf.ByteString.EMPTY;
      bluetoothMac_ = 0;
      bluetoothAnonmymous_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < internetIpv4_.size(); i++) {
        output.writeFixed32(10, internetIpv4_.get(i));
      }
      for (int i = 0; i < internetIpv6_.size(); i++) {
        output.writeBytes(11, internetIpv6_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(20, bssid_);
      }
      for (int i = 0; i < intranetIpv4_.size(); i++) {
        output.writeFixed32(21, intranetIpv4_.get(i));
      }
      for (int i = 0; i < intranetIpv6_.size(); i++) {
        output.writeBytes(22, intranetIpv6_.get(i));
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFixed32(30, bluetoothMac_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(31, bluetoothAnonmymous_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        dataSize = 4 * getInternetIpv4List().size();
        size += dataSize;
        size += 1 * getInternetIpv4List().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < internetIpv6_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(internetIpv6_.get(i));
        }
        size += dataSize;
        size += 1 * getInternetIpv6List().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(20, bssid_);
      }
      {
        int dataSize = 0;
        dataSize = 4 * getIntranetIpv4List().size();
        size += dataSize;
        size += 2 * getIntranetIpv4List().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < intranetIpv6_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(intranetIpv6_.get(i));
        }
        size += dataSize;
        size += 2 * getIntranetIpv6List().size();
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(30, bluetoothMac_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(31, bluetoothAnonmymous_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.remoteandroid.ui.connect.ConnectMessages.Candidates parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.remoteandroid.ui.connect.ConnectMessages.Candidates prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.remoteandroid.ui.connect.ConnectMessages.Candidates, Builder>
        implements org.remoteandroid.ui.connect.ConnectMessages.CandidatesOrBuilder {
      // Construct using org.remoteandroid.ui.connect.ConnectMessages.Candidates.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        internetIpv4_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        internetIpv6_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        intranetIpv4_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        intranetIpv6_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        bssid_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        bluetoothMac_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        bluetoothAnonmymous_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public org.remoteandroid.ui.connect.ConnectMessages.Candidates getDefaultInstanceForType() {
        return org.remoteandroid.ui.connect.ConnectMessages.Candidates.getDefaultInstance();
      }
      
      public org.remoteandroid.ui.connect.ConnectMessages.Candidates build() {
        org.remoteandroid.ui.connect.ConnectMessages.Candidates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.remoteandroid.ui.connect.ConnectMessages.Candidates buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.remoteandroid.ui.connect.ConnectMessages.Candidates result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.remoteandroid.ui.connect.ConnectMessages.Candidates buildPartial() {
        org.remoteandroid.ui.connect.ConnectMessages.Candidates result = new org.remoteandroid.ui.connect.ConnectMessages.Candidates(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          internetIpv4_ = java.util.Collections.unmodifiableList(internetIpv4_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.internetIpv4_ = internetIpv4_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          internetIpv6_ = java.util.Collections.unmodifiableList(internetIpv6_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.internetIpv6_ = internetIpv6_;
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          intranetIpv4_ = java.util.Collections.unmodifiableList(intranetIpv4_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.intranetIpv4_ = intranetIpv4_;
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          intranetIpv6_ = java.util.Collections.unmodifiableList(intranetIpv6_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.intranetIpv6_ = intranetIpv6_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000001;
        }
        result.bssid_ = bssid_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000002;
        }
        result.bluetoothMac_ = bluetoothMac_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000004;
        }
        result.bluetoothAnonmymous_ = bluetoothAnonmymous_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(org.remoteandroid.ui.connect.ConnectMessages.Candidates other) {
        if (other == org.remoteandroid.ui.connect.ConnectMessages.Candidates.getDefaultInstance()) return this;
        if (!other.internetIpv4_.isEmpty()) {
          if (internetIpv4_.isEmpty()) {
            internetIpv4_ = other.internetIpv4_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureInternetIpv4IsMutable();
            internetIpv4_.addAll(other.internetIpv4_);
          }
          
        }
        if (!other.internetIpv6_.isEmpty()) {
          if (internetIpv6_.isEmpty()) {
            internetIpv6_ = other.internetIpv6_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureInternetIpv6IsMutable();
            internetIpv6_.addAll(other.internetIpv6_);
          }
          
        }
        if (!other.intranetIpv4_.isEmpty()) {
          if (intranetIpv4_.isEmpty()) {
            intranetIpv4_ = other.intranetIpv4_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureIntranetIpv4IsMutable();
            intranetIpv4_.addAll(other.intranetIpv4_);
          }
          
        }
        if (!other.intranetIpv6_.isEmpty()) {
          if (intranetIpv6_.isEmpty()) {
            intranetIpv6_ = other.intranetIpv6_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureIntranetIpv6IsMutable();
            intranetIpv6_.addAll(other.intranetIpv6_);
          }
          
        }
        if (other.hasBssid()) {
          setBssid(other.getBssid());
        }
        if (other.hasBluetoothMac()) {
          setBluetoothMac(other.getBluetoothMac());
        }
        if (other.hasBluetoothAnonmymous()) {
          setBluetoothAnonmymous(other.getBluetoothAnonmymous());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 85: {
              ensureInternetIpv4IsMutable();
              internetIpv4_.add(input.readFixed32());
              break;
            }
            case 82: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addInternetIpv4(input.readFixed32());
              }
              input.popLimit(limit);
              break;
            }
            case 90: {
              ensureInternetIpv6IsMutable();
              internetIpv6_.add(input.readBytes());
              break;
            }
            case 162: {
              bitField0_ |= 0x00000010;
              bssid_ = input.readBytes();
              break;
            }
            case 173: {
              ensureIntranetIpv4IsMutable();
              intranetIpv4_.add(input.readFixed32());
              break;
            }
            case 170: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addIntranetIpv4(input.readFixed32());
              }
              input.popLimit(limit);
              break;
            }
            case 178: {
              ensureIntranetIpv6IsMutable();
              intranetIpv6_.add(input.readBytes());
              break;
            }
            case 245: {
              bitField0_ |= 0x00000020;
              bluetoothMac_ = input.readFixed32();
              break;
            }
            case 248: {
              bitField0_ |= 0x00000040;
              bluetoothAnonmymous_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated fixed32 internetIpv4 = 10;
      private java.util.List<java.lang.Integer> internetIpv4_ = java.util.Collections.emptyList();;
      private void ensureInternetIpv4IsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          internetIpv4_ = new java.util.ArrayList<java.lang.Integer>(internetIpv4_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getInternetIpv4List() {
        return java.util.Collections.unmodifiableList(internetIpv4_);
      }
      public int getInternetIpv4Count() {
        return internetIpv4_.size();
      }
      public int getInternetIpv4(int index) {
        return internetIpv4_.get(index);
      }
      public Builder setInternetIpv4(
          int index, int value) {
        ensureInternetIpv4IsMutable();
        internetIpv4_.set(index, value);
        
        return this;
      }
      public Builder addInternetIpv4(int value) {
        ensureInternetIpv4IsMutable();
        internetIpv4_.add(value);
        
        return this;
      }
      public Builder addAllInternetIpv4(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureInternetIpv4IsMutable();
        super.addAll(values, internetIpv4_);
        
        return this;
      }
      public Builder clearInternetIpv4() {
        internetIpv4_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        
        return this;
      }
      
      // repeated bytes internetIpv6 = 11;
      private java.util.List<com.google.protobuf.ByteString> internetIpv6_ = java.util.Collections.emptyList();;
      private void ensureInternetIpv6IsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          internetIpv6_ = new java.util.ArrayList<com.google.protobuf.ByteString>(internetIpv6_);
          bitField0_ |= 0x00000002;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getInternetIpv6List() {
        return java.util.Collections.unmodifiableList(internetIpv6_);
      }
      public int getInternetIpv6Count() {
        return internetIpv6_.size();
      }
      public com.google.protobuf.ByteString getInternetIpv6(int index) {
        return internetIpv6_.get(index);
      }
      public Builder setInternetIpv6(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInternetIpv6IsMutable();
        internetIpv6_.set(index, value);
        
        return this;
      }
      public Builder addInternetIpv6(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureInternetIpv6IsMutable();
        internetIpv6_.add(value);
        
        return this;
      }
      public Builder addAllInternetIpv6(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureInternetIpv6IsMutable();
        super.addAll(values, internetIpv6_);
        
        return this;
      }
      public Builder clearInternetIpv6() {
        internetIpv6_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000002);
        
        return this;
      }
      
      // repeated fixed32 intranetIpv4 = 21;
      private java.util.List<java.lang.Integer> intranetIpv4_ = java.util.Collections.emptyList();;
      private void ensureIntranetIpv4IsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          intranetIpv4_ = new java.util.ArrayList<java.lang.Integer>(intranetIpv4_);
          bitField0_ |= 0x00000004;
         }
      }
      public java.util.List<java.lang.Integer>
          getIntranetIpv4List() {
        return java.util.Collections.unmodifiableList(intranetIpv4_);
      }
      public int getIntranetIpv4Count() {
        return intranetIpv4_.size();
      }
      public int getIntranetIpv4(int index) {
        return intranetIpv4_.get(index);
      }
      public Builder setIntranetIpv4(
          int index, int value) {
        ensureIntranetIpv4IsMutable();
        intranetIpv4_.set(index, value);
        
        return this;
      }
      public Builder addIntranetIpv4(int value) {
        ensureIntranetIpv4IsMutable();
        intranetIpv4_.add(value);
        
        return this;
      }
      public Builder addAllIntranetIpv4(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureIntranetIpv4IsMutable();
        super.addAll(values, intranetIpv4_);
        
        return this;
      }
      public Builder clearIntranetIpv4() {
        intranetIpv4_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000004);
        
        return this;
      }
      
      // repeated bytes intranetIpv6 = 22;
      private java.util.List<com.google.protobuf.ByteString> intranetIpv6_ = java.util.Collections.emptyList();;
      private void ensureIntranetIpv6IsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          intranetIpv6_ = new java.util.ArrayList<com.google.protobuf.ByteString>(intranetIpv6_);
          bitField0_ |= 0x00000008;
         }
      }
      public java.util.List<com.google.protobuf.ByteString>
          getIntranetIpv6List() {
        return java.util.Collections.unmodifiableList(intranetIpv6_);
      }
      public int getIntranetIpv6Count() {
        return intranetIpv6_.size();
      }
      public com.google.protobuf.ByteString getIntranetIpv6(int index) {
        return intranetIpv6_.get(index);
      }
      public Builder setIntranetIpv6(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIntranetIpv6IsMutable();
        intranetIpv6_.set(index, value);
        
        return this;
      }
      public Builder addIntranetIpv6(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureIntranetIpv6IsMutable();
        intranetIpv6_.add(value);
        
        return this;
      }
      public Builder addAllIntranetIpv6(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureIntranetIpv6IsMutable();
        super.addAll(values, intranetIpv6_);
        
        return this;
      }
      public Builder clearIntranetIpv6() {
        intranetIpv6_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000008);
        
        return this;
      }
      
      // optional bytes bssid = 20;
      private com.google.protobuf.ByteString bssid_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasBssid() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getBssid() {
        return bssid_;
      }
      public Builder setBssid(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        bssid_ = value;
        
        return this;
      }
      public Builder clearBssid() {
        bitField0_ = (bitField0_ & ~0x00000010);
        bssid_ = getDefaultInstance().getBssid();
        
        return this;
      }
      
      // optional fixed32 bluetoothMac = 30;
      private int bluetoothMac_ ;
      public boolean hasBluetoothMac() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public int getBluetoothMac() {
        return bluetoothMac_;
      }
      public Builder setBluetoothMac(int value) {
        bitField0_ |= 0x00000020;
        bluetoothMac_ = value;
        
        return this;
      }
      public Builder clearBluetoothMac() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bluetoothMac_ = 0;
        
        return this;
      }
      
      // optional bool bluetoothAnonmymous = 31;
      private boolean bluetoothAnonmymous_ ;
      public boolean hasBluetoothAnonmymous() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public boolean getBluetoothAnonmymous() {
        return bluetoothAnonmymous_;
      }
      public Builder setBluetoothAnonmymous(boolean value) {
        bitField0_ |= 0x00000040;
        bluetoothAnonmymous_ = value;
        
        return this;
      }
      public Builder clearBluetoothAnonmymous() {
        bitField0_ = (bitField0_ & ~0x00000040);
        bluetoothAnonmymous_ = false;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:org.remoteandroid.ui.connect.Candidates)
    }
    
    static {
      defaultInstance = new Candidates(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:org.remoteandroid.ui.connect.Candidates)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
